# - Append '-' to names that are also prefixes of related projects. Allows find-window to exact match.
# - Prepend 'v' to vim windows.
# - Prepend 't' to terminal-only windows.
#  - Set VIM_PORT for dockerized-vim wrapper script
windows:
  - name: "t1"
    root: "~/"
    layout: even-vertical
    panes:
      - tail -F ~/error.log
      - commands:
          - clear
        focus: true
  - name: "vim"
    root: "~/"
    layout: even-vertical
    panes:
      - vimsh
      - commands:
          - vimide
        focus: true
  - name: "t3"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - vim3000
        focus: true
  - name: "t4"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
  - name: "t5"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
  - name: "t6"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
  - name: "t7"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
  - name: "t8"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
  - name: "t9"
    root: "~/"
    layout: even-vertical
    panes:
      - clear
      - commands:
          - clear
        focus: true
