# - Append '-' to names that are also prefixes of related projects. Allows find-window to exact match.
# - Prepend 'v' to vim windows.
# - Prepend 't' to terminal-only windows.
#  - Set VIM_PORT for dockerized-vim wrapper script
windows:
  - name: "vdef"
    root: "/var/dev/"
    panes:
      - viminit && VIM_PORT=3000 VIM_NAME=vim vim
  - name: "tdef"
    root: "/var/dev/"
    panes:
      - clear; echo "Loaded tdef"
  - name: "t4"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t4"
  - name: "t5"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t5"
  - name: "t6"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t6"
  - name: "t7"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t8"
  - name: "t8"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t8"
  - name: "t9"
    root: "/var/dev"
    panes:
      - clear; echo "Loaded t9"
